repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: | 
            (?x) (
                (^|/)etc/ 
            )
        args:
            - "--config=.flake8-config"
        additional_dependencies: [
            pycodestyle==2.8.0,
            flake8-bugbear==20.1.4,
            flake8-builtins==1.5.3,
            flake8-comprehensions==3.7.0,
            flake8-import-order==0.18.1,
            pep8-naming==0.9.1
        ]
